baseURL = 'https://talhahmad.me/'
languageCode = 'en-us'
title = 'Talha Ahmad'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Talha Ahmad personal website"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = true

# Intro on main page, content is markdown
homeIntroTitle = 'Musician who Sometimes Builds Things'
homeIntroContent = """
I'm a mechtronics engineering student who enjoys making projects and composing music. To learn more about my background please read my [about page](/about) and check me out on [LinkedIn](https://www.linkedin.com/in/talha-a-ahmad/). This site is where I plan on showcasing my projects as well as all my socials so you can follow me on my journey.
"""

# Collection to display on home
# homeCollectionTitle = 'Recent Musings'
# homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/talha-a-ahmad/"

[[params.social]]
name = "github"
url = "https://github.com/bigboichickennugget"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
